name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-20.04
    name: test-swig-build-action
    steps:
    - uses: actions/checkout@v3
    - name: swig build
      uses: ./
      with:
        version: 4.0.2
    - name: swig version
      run: swig -version